Add review function to FAME
certsocietegenerale/fame pull request #100
Opened 2022-02-24 16:22 UTC by Tiagojdc

### Changes
Add a review features which will help analyst to work in collaboration.

It adds a permission named "review" which allow users to access to a new page. This page contain sames elements as on index page, but with the possibility to review them and filter reviewed elements

2022-03-02 13:38 UTC, gaelmuller requested changes
Thank you for your contribution ! I think this is a useful feature but it would need some adjustments before we can merge it in my opinion:

* It is currently introducing a bug that is breaking the "Object Details" page
* I think that the review status should be handled like the sharing groups: be attached to the object and duplicated inside analyses
* I don't see the point of having a different page. We could use the analyses page directly and use the permission to display (or not) the additional column & filters

2022-03-02 13:38 UTC, gaelmuller commented on web/templates/files/details.html
> +                        <form method="POST" action="/analyses/{{analysis._id}}/reviewed">
We can't do this because `analysis` will not be defined when looking at the object's page.

2022-03-02 13:38 UTC, gaelmuller commented on web/templates/files/details.html
> +                    <span class="filter-btn">
This should only appear if the user has the appropriate permission

2023-05-03 16:45 UTC, Augustin-FL commented
Hi @gaelmuller 

May I request a second review of this PR ?

If needed, I have merged the PR to a temporary branch https://github.com/Augustin-FL/fame/tree/review, you can test it with docker:
```
git clone https://github.com/Augustin-FL/fame.git
cd fame/docker
git checkout review
cp fame.env.template fame.env
echo "DEFAULT_EMAIL=admin@changeme.fame" >> fame.env
echo "DEFAULT_PASSWORD=changeme" >> fame.env
docker-compose up --build
```

2023-05-09 09:23 UTC, Augustin-FL commented
Hi,

I will merge this. 
if you have some comments to make on this PR, feel free to let them here (even after the merge)

2023-05-09 09:27 UTC, merged